echo "cîga+1Sg+Dec" | flookup -i sto.foma
echo "cîga+2Sg+Dec" | flookup -i sto.foma
echo "cîga+3Sg+Dec" | flookup -i sto.foma
echo "cîga+1Pl+Dec" | flookup -i sto.foma
echo "cîga+2Pl+Dec" | flookup -i sto.foma
echo "cîga+3Pl+Dec" | flookup -i sto.foma
echo "maní+1Sg+Dec" | flookup -i sto.foma
echo "maní+2Sg+Dec" | flookup -i sto.foma
echo "maní+3Sg+Dec" | flookup -i sto.foma
echo "maní+1Pl+Dec" | flookup -i sto.foma
echo "maní+2Pl+Dec" | flookup -i sto.foma
echo "maní+3Pl+Dec" | flookup -i sto.foma
echo "agdaa+1Sg+Dec" | flookup -i sto.foma
echo "agdaa+2Sg+Dec" | flookup -i sto.foma
echo "agdaa+3Sg+Dec" | flookup -i sto.foma
echo "agdaa+1Pl+Dec" | flookup -i sto.foma
echo "agdaa+2Pl+Dec" | flookup -i sto.foma
echo "agdaa+3Pl+Dec" | flookup -i sto.foma
echo "yúda+1Sg+Dec" | flookup -i sto.foma
echo "yúda+2Sg+Dec" | flookup -i sto.foma
echo "yúda+3Sg+Dec" | flookup -i sto.foma
echo "yúda+1Pl+Dec" | flookup -i sto.foma
echo "yúda+2Pl+Dec" | flookup -i sto.foma
echo "yúda+3Pl+Dec" | flookup -i sto.foma
echo "yagda+1Sg+Dec" | flookup -i sto.foma
echo "yagda+2Sg+Dec" | flookup -i sto.foma
echo "yagda+3Sg+Dec" | flookup -i sto.foma
echo "yagda+1Pl+Dec" | flookup -i sto.foma
echo "yagda+2Pl+Dec" | flookup -i sto.foma
echo "yagda+3Pl+Dec" | flookup -i sto.foma
echo "iyo+1Sg+Dec" | flookup -i sto.foma
echo "iyo+2Sg+Dec" | flookup -i sto.foma
echo "iyo+3Sg+Dec" | flookup -i sto.foma
echo "iyo+1Pl+Dec" | flookup -i sto.foma
echo "iyo+2Pl+Dec" | flookup -i sto.foma
echo "iyo+3Pl+Dec" | flookup -i sto.foma
echo "ishdima+1Sg+Dec" | flookup -i sto.foma
echo "ishdima+2Sg+Dec" | flookup -i sto.foma
echo "ishdima+3Sg+Dec" | flookup -i sto.foma
echo "ishdima+1Pl+Dec" | flookup -i sto.foma
echo "ishdima+2Pl+Dec" | flookup -i sto.foma
echo "ishdima+3Pl+Dec" | flookup -i sto.foma
echo "hnagda+1Sg+Dec" | flookup -i sto.foma
echo "hnagda+2Sg+Dec" | flookup -i sto.foma
echo "hnagda+3Sg+Dec" | flookup -i sto.foma
echo "hnagda+1Pl+Dec" | flookup -i sto.foma
echo "hnagda+2Pl+Dec" | flookup -i sto.foma
echo "hnagda+3Pl+Dec" | flookup -i sto.foma
echo "nata+1Sg+2SgO+Dec" | flookup -i sto.foma
echo "nata+1Sg+3SgO+Dec" | flookup -i sto.foma
echo "nata+2Sg+1SgO+Dec" | flookup -i sto.foma
echo "nata+2Sg+3SgO+Dec" | flookup -i sto.foma
echo "nata+3Sg+1SgO+Dec" | flookup -i sto.foma
echo "nata+3Sg+2SgO+Dec" | flookup -i sto.foma
echo "nata+3Sg+3SgO+Dec" | flookup -i sto.foma
echo "uge+1Sg+2SgO+Dec" | flookup -i sto.foma
echo "uge+1Sg+3SgO+Dec" | flookup -i sto.foma
echo "uge+1Sg+2PlO+Dec" | flookup -i sto.foma
echo "uge+1Sg+3PlO+Dec" | flookup -i sto.foma
echo "uge+2Sg+1SgO+Dec" | flookup -i sto.foma
echo "uge+2Sg+3SgO+Dec" | flookup -i sto.foma
echo "uge+2Sg+1PlO+Dec" | flookup -i sto.foma
echo "uge+2Sg+3PlO+Dec" | flookup -i sto.foma
echo "uge+3Sg+1SgO+Dec" | flookup -i sto.foma
echo "uge+3Sg+2SgO+Dec" | flookup -i sto.foma
echo "uge+3Sg+3SgO+Dec" | flookup -i sto.foma
echo "uge+3Sg+1PlO+Dec" | flookup -i sto.foma
echo "uge+3Sg+2PlO+Dec" | flookup -i sto.foma
echo "uge+3Sg+3PlO+Dec" | flookup -i sto.foma
echo "uge+1Pl+2SgO+Dec" | flookup -i sto.foma
echo "uge+1Pl+3SgO+Dec" | flookup -i sto.foma
echo "uge+1Pl+2PlO+Dec" | flookup -i sto.foma
echo "uge+1Pl+3PlO+Dec" | flookup -i sto.foma
echo "uge+2Pl+1SgO+Dec" | flookup -i sto.foma
echo "uge+2Pl+3SgO+Dec" | flookup -i sto.foma
echo "uge+2Pl+1PlO+Dec" | flookup -i sto.foma
echo "uge+2Pl+3PlO+Dec" | flookup -i sto.foma
echo "uge+3Pl+1SgO+Dec" | flookup -i sto.foma
echo "uge+3Pl+2SgO+Dec" | flookup -i sto.foma
echo "uge+3Pl+3SgO+Dec" | flookup -i sto.foma
echo "uge+3Pl+1PlO+Dec" | flookup -i sto.foma
echo "uge+3Pl+2PlO+Dec" | flookup -i sto.foma
echo "uge+3Pl+3PlO+Dec" | flookup -i sto.foma