echo "wacîgad" | flookup sto.foma
echo "yacîgad" | flookup sto.foma
echo "cîgad" | flookup sto.foma
echo "icîgabid" | flookup sto.foma
echo "yacîgabid" | flookup sto.foma
echo "cîgabid" | flookup sto.foma
echo "maunid" | flookup sto.foma
echo "maanid" | flookup sto.foma
echo "manid" | flookup sto.foma
echo "imanimid" | flookup sto.foma
echo "maanimid" | flookup sto.foma
echo "manimid" | flookup sto.foma
echo "augdaad" | flookup sto.foma
echo "aagdaad" | flookup sto.foma
echo "agdaad" | flookup sto.foma
echo "agigdaabid" | flookup sto.foma
echo "aagdaabid" | flookup sto.foma
echo "agdaabid" | flookup sto.foma
echo "mudad" | flookup sto.foma
echo "nudad" | flookup sto.foma
echo "yudad" | flookup sto.foma
echo "igudabid" | flookup sto.foma
echo "nudabid" | flookup sto.foma
echo "yudabid" | flookup sto.foma
echo "magdad" | flookup sto.foma
echo "nagdad" | flookup sto.foma
echo "yagdad" | flookup sto.foma
echo "igagdamid" | flookup sto.foma
echo "nagdamid" | flookup sto.foma
echo "yagdamid" | flookup sto.foma
echo "imod" | flookup sto.foma
echo "inod" | flookup sto.foma
echo "iyod" | flookup sto.foma
echo "igiyobid" | flookup sto.foma
echo "inobid" | flookup sto.foma
echo "iyobid" | flookup sto.foma
echo "mishdimad" | flookup sto.foma
echo "nishdimad" | flookup sto.foma
echo "ishdimad" | flookup sto.foma
echo "igishdimamid" | flookup sto.foma
echo "nishdimamid" | flookup sto.foma
echo "ishdimamid" | flookup sto.foma
echo "wahnagdad" | flookup sto.foma
echo "yahnagdad" | flookup sto.foma
echo "hnagdad" | flookup sto.foma
echo "ihnagdamid" | flookup sto.foma
echo "yahnagdamid" | flookup sto.foma
echo "hnagdamid" | flookup sto.foma
echo "nacitad" | flookup sto.foma
echo "nautad" | flookup sto.foma
echo "namaatad" | flookup sto.foma
echo "naatad" | flookup sto.foma
echo "namatad" | flookup sto.foma
echo "nanitad" | flookup sto.foma
echo "natad" | flookup sto.foma
echo "uciged" | flookup sto.foma
echo "uwaged" | flookup sto.foma
echo "ucigebid" | flookup sto.foma
echo "uwicauged" | flookup sto.foma
echo "umaaged" | flookup sto.foma
echo "uyaged" | flookup sto.foma
echo "ugiyagebid" | flookup sto.foma
echo "uwicaaged" | flookup sto.foma
echo "umaged" | flookup sto.foma
echo "uniged" | flookup sto.foma
echo "uged" | flookup sto.foma
echo "ugigebid" | flookup sto.foma
echo "unigebid" | flookup sto.foma
echo "uwicaged" | flookup sto.foma
echo "uginigebid" | flookup sto.foma
echo "ugigebid" | flookup sto.foma
echo "uginigebid" | flookup sto.foma
echo "uwicagigebid" | flookup sto.foma
echo "umaagebid" | flookup sto.foma
echo "uyagebid" | flookup sto.foma
echo "ugiyagebid" | flookup sto.foma
echo "uwicaagebid" | flookup sto.foma
echo "umagebid" | flookup sto.foma
echo "unigebid" | flookup sto.foma
echo "ugebid" | flookup sto.foma
echo "ugigebid" | flookup sto.foma
echo "unigebid" | flookup sto.foma
echo "uwicagebid" | flookup sto.foma